PFMS Assignment 3 | 14250803: Graph Class Reference
Graph Class Reference
Graph class for representing traversability routes between waypoints.
#include <graph.h>
Public Member Functions
Graph (size_t num_nodes)
Constructor for Graph.
void addEdge (size_t from, size_t to, double cost)
Add an edge between two nodes (bidirectional)
const std::vector< Edge > & getEdges (size_t node) const
Get all edges from a specific node.
size_t getNumNodes () const
Get the number of nodes in the graph.
bool hasEdge (size_t from, size_t to) const
Check if there's a direct edge between two nodes.
double getEdgeCost (size_t from, size_t to) const
Get the cost of the edge between two nodes.
std::vector< size_t > findShortestPath (size_t start, size_t end) const
Find shortest path between two nodes using Dijkstra's algorithm.
double calculatePathCost (const std::vector< size_t > &path) const
Calculate total cost of a given path.
std::vector< std::vector< size_t > > getAllPaths (size_t start, size_t end, size_t max_depth=10) const
Get all possible paths between two nodes (up to a maximum depth)
void printGraphInfo (const rclcpp::Logger &logger) const
Print graph statistics and connectivity information.
std::vector< std::vector< double > > getAdjacencyMatrix () const
Get connectivity matrix (for visualisation or analysis)
Detailed Description
Graph class for representing traversability routes between waypoints.
Definition at line 23 of file graph.h.
Constructor & Destructor Documentation
Graph()
Graph::Graph (size_t num_nodes) explicit
Constructor for Graph.
Parameters
num_nodes Number of nodes (waypoints) in the graph
Definition at line 6 of file graph.cpp.
Member Function Documentation
addEdge()
void Graph::addEdge (size_t from, size_t to, double cost)
Add an edge between two nodes (bidirectional)
Parameters
from Source node index
to Destination node index
cost Cost/distance of the edge
Definition at line 10 of file graph.cpp.
calculatePathCost()
double Graph::calculatePathCost (const std::vector< size_t > & path) const
Calculate total cost of a given path.
Parameters
path Vector of node indices representing the path
Returns
Total cost of the path
Definition at line 113 of file graph.cpp.
References getEdgeCost().
findShortestPath()
std::vector< size_t > Graph::findShortestPath (size_t start, size_t end) const
Find shortest path between two nodes using Dijkstra's algorithm.
Parameters
start Start node index
end End node index
Returns
Vector of node indices representing the shortest path
Definition at line 54 of file graph.cpp.
getAdjacencyMatrix()
std::vector< std::vector< double > > Graph::getAdjacencyMatrix () const
Get connectivity matrix (for visualisation or analysis)
Returns
2D vector representing the adjacency matrix with costs
Definition at line 194 of file graph.cpp.
getAllPaths()
std::vector< std::vector< size_t > > Graph::getAllPaths (size_t start, size_t end, size_t max_depth = 10) const
Get all possible paths between two nodes (up to a maximum depth)
Parameters
start Start node index
end End node index
max_depth Maximum search depth to prevent infinite loops
Returns
Vector of paths, each path is a vector of node indices
Definition at line 130 of file graph.cpp.
getEdgeCost()
double Graph::getEdgeCost (size_t from, size_t to) const
Get the cost of the edge between two nodes.
Parameters
from Source node
to Destination node
Returns
Cost of the edge, or infinity if no edge exists
Definition at line 42 of file graph.cpp.
References hasEdge().
Referenced by calculatePathCost().
getEdges()
const std::vector< Edge > & Graph::getEdges (size_t node) const
Get all edges from a specific node.
Parameters
node Node index
Returns
Vector of edges from the node
Definition at line 20 of file graph.cpp.
getNumNodes()
size_t Graph::getNumNodes () const
Get the number of nodes in the graph.
Returns
Number of nodes
Definition at line 28 of file graph.cpp.
hasEdge()
bool Graph::hasEdge (size_t from, size_t to) const
Check if there's a direct edge between two nodes.
Parameters
from Source node
to Destination node
Returns
true if edge exists, false otherwise
Definition at line 32 of file graph.cpp.
Referenced by getEdgeCost().
printGraphInfo()
void Graph::printGraphInfo (const rclcpp::Logger & logger) const
Print graph statistics and connectivity information.
Parameters
logger ROS logger for output
Definition at line 172 of file graph.cpp.
The documentation for this class was generated from the following files:
include/graph.h
src/graph.cpp