PFMS Assignment 3 | 14250803: Controller Class Reference
Controller Class Reference
#include <controller.h>
Public Member Functions
Controller (const rclcpp::Publisher< geometry_msgs::msg::Twist >::SharedPtr &cmd_vel_pub, const rclcpp::Publisher< std_msgs::msg::Empty >::SharedPtr &takeoff_pub, const rclcpp::Publisher< std_msgs::msg::Empty >::SharedPtr &land_pub, const rclcpp::Logger &logger)
Constructor for Controller.
bool processCommand (VehicleData &vehicle, const VehicleData::Command &command)
Process a vehicle's command.
void startMission (VehicleData &vehicle)
Start a mission for a vehicle.
void stopMission (VehicleData &vehicle)
Stop the mission for a vehicle.
bool takeoff (VehicleData &vehicle)
Command the drone to take off.
bool land (VehicleData &vehicle)
Command the drone to land.
bool flyToGoal (VehicleData &vehicle, const geometry_msgs::msg::Pose &goal)
Fly to a goal position.
double calculateDistance (const geometry_msgs::msg::Point &p1, const geometry_msgs::msg::Point &p2)
Calculate the distance between two points.
void abortMission (VehicleData &vehicle)
Abort mission if waypoints are not traversable.
bool checkForObstacles (const sensor_msgs::msg::LaserScan::SharedPtr &laser_scan)
Check for obstacles using laser data (360-degree emergency detection)
double calculateAltitudeAdjustment (double current_altitude, double sonar_range)
Calculate altitude adjustment based on sonar reading.
void setAltitudeAdjustment (double adjustment)
Set the current altitude adjustment Used to maintain altitude control during flight.
bool checkObstaclesInDirection (const sensor_msgs::msg::LaserScan::SharedPtr &laser_scan, const geometry_msgs::msg::Point &current_pos, const geometry_msgs::msg::Point &target_pos)
Check for obstacles in the direction of travel.
bool isObstacleClearanceAchieved (const sensor_msgs::msg::LaserScan::SharedPtr &laser_scan, const geometry_msgs::msg::Point &current_pos, const geometry_msgs::msg::Point &target_pos, double clearance_distance=4.0)
Check if obstacle clearance has been achieved.
Detailed Description
Definition at line 6 of file controller.h.
Constructor & Destructor Documentation
Controller()
Controller::Controller (const rclcpp::Publisher< geometry_msgs::msg::Twist >::SharedPtr & cmd_vel_pub, const rclcpp::Publisher< std_msgs::msg::Empty >::SharedPtr & takeoff_pub, const rclcpp::Publisher< std_msgs::msg::Empty >::SharedPtr & land_pub, const rclcpp::Logger & logger)
Constructor for Controller.
Parameters
cmd_vel_pub Publisher for velocity commands
takeoff_pub Publisher for takeoff commands
land_pub Publisher for landing commands
logger Logger to use
Definition at line 5 of file controller.cpp.
Member Function Documentation
abortMission()
void Controller::abortMission (VehicleData & vehicle)
Abort mission if waypoints are not traversable.
Computes the Euclidean distance between two positions
Parameters
vehicle Vehicle data
Definition at line 322 of file controller.cpp.
References calculateDistance(), VehicleData::command_queue, VehicleData::current_odom, VehicleData::Command::FLYING, VehicleData::id, VehicleData::Command::LANDING, VehicleData::mission_active, VehicleData::odom_mutex, VehicleData::queue_cv, VehicleData::queue_mutex, and VehicleData::start_position.
calculateAltitudeAdjustment()
double Controller::calculateAltitudeAdjustment (double current_altitude, double sonar_range)
Calculate altitude adjustment based on sonar reading.
Parameters
current_altitude Current drone altitude
sonar_range Distance to ground from sonar
Returns
Vertical velocity adjustment
Definition at line 432 of file controller.cpp.
calculateDistance()
double Controller::calculateDistance (const geometry_msgs::msg::Point & p1, const geometry_msgs::msg::Point & p2)
Calculate the distance between two points.
Computes the Euclidean distance between two positions
Parameters
p1 First position
p2 Second position
Returns
Distance in meters
Definition at line 544 of file controller.cpp.
Referenced by abortMission().
checkForObstacles()
bool Controller::checkForObstacles (const sensor_msgs::msg::LaserScan::SharedPtr & laser_scan)
Check for obstacles using laser data (360-degree emergency detection)
Scans all laser readings for very close obstacles that require immediate emergency ascent regardless of travel direction.
Parameters
laser_scan Latest laser scan data
Returns
true if critical obstacle detected requiring emergency ascent, false otherwise
Definition at line 364 of file controller.cpp.
checkObstaclesInDirection()
bool Controller::checkObstaclesInDirection (const sensor_msgs::msg::LaserScan::SharedPtr & laser_scan, const geometry_msgs::msg::Point & current_pos, const geometry_msgs::msg::Point & target_pos)
Check for obstacles in the direction of travel.
Parameters
laser_scan Latest laser scan data
current_pos Current drone position
target_pos Target position we're navigating to
Returns
true if obstacle detected in travel direction, false otherwise
Definition at line 554 of file controller.cpp.
flyToGoal()
bool Controller::flyToGoal (VehicleData & vehicle, const geometry_msgs::msg::Pose & goal)
Fly to a goal position.
Controls the drone to reach a specified goal position
Parameters
vehicle Vehicle data
goal The goal position to reach
Returns
true if goal reached successfully, false otherwise
Definition at line 192 of file controller.cpp.
References VehicleData::current_odom, VehicleData::id, VehicleData::mission_active, and VehicleData::odom_mutex.
Referenced by processCommand().
isObstacleClearanceAchieved()
bool Controller::isObstacleClearanceAchieved (const sensor_msgs::msg::LaserScan::SharedPtr & laser_scan, const geometry_msgs::msg::Point & current_pos, const geometry_msgs::msg::Point & target_pos, double clearance_distance = 4.0)
Check if obstacle clearance has been achieved.
Parameters
laser_scan Latest laser scan data
current_pos Current drone position
target_pos Target position we're navigating to
clearance_distance Minimum clearance distance required
Returns
true if path is clear, false if obstacles still present
Definition at line 632 of file controller.cpp.
land()
bool Controller::land (VehicleData & vehicle)
Command the drone to land.
Sends the drone landing command
Parameters
vehicle Vehicle data
Returns
true if landing command sent successfully
Definition at line 180 of file controller.cpp.
References VehicleData::id, and VehicleData::takeoff_complete.
Referenced by processCommand().
processCommand()
bool Controller::processCommand (VehicleData & vehicle, const VehicleData::Command & command)
Process a vehicle's command.
Executes a command from the vehicle's queue
Parameters
vehicle Vehicle data
command Command to execute
Returns
true if command executed successfully, false otherwise
Definition at line 17 of file controller.cpp.
References VehicleData::Command::FLYING, flyToGoal(), VehicleData::Command::goal, VehicleData::id, land(), VehicleData::Command::LANDING, VehicleData::mission_active, VehicleData::Command::STOP, VehicleData::Command::TAKEOFF, takeoff(), and VehicleData::Command::type.
setAltitudeAdjustment()
void Controller::setAltitudeAdjustment (double adjustment) inline
Set the current altitude adjustment Used to maintain altitude control during flight.
Definition at line 118 of file controller.h.
startMission()
void Controller::startMission (VehicleData & vehicle)
Start a mission for a vehicle.
Creates and queues commands for a complete mission
Parameters
vehicle Vehicle data
Definition at line 45 of file controller.cpp.
References VehicleData::command_queue, VehicleData::current_goal_index, VehicleData::Command::FLYING, VehicleData::goals, VehicleData::goals_mutex, VehicleData::mission_active, VehicleData::mission_progress, VehicleData::queue_cv, VehicleData::queue_mutex, VehicleData::Command::TAKEOFF, and VehicleData::takeoff_complete.
stopMission()
void Controller::stopMission (VehicleData & vehicle)
Stop the mission for a vehicle.
Clears command queue and adds a STOP command
Parameters
vehicle Vehicle data
Definition at line 86 of file controller.cpp.
References VehicleData::command_queue, VehicleData::Command::LANDING, VehicleData::queue_cv, VehicleData::queue_mutex, and VehicleData::Command::STOP.
takeoff()
bool Controller::takeoff (VehicleData & vehicle)
Command the drone to take off.
Sends the drone takeoff command and monitors altitude
Parameters
vehicle Vehicle data
Returns
true if takeoff successful, false otherwise
Definition at line 105 of file controller.cpp.
References VehicleData::current_odom, VehicleData::id, VehicleData::odom_mutex, and VehicleData::takeoff_complete.
Referenced by processCommand().
The documentation for this class was generated from the following files:
include/controller.h
src/controller.cpp